# .gitpod.yml
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - nextflow.nextflow

# Increase memory and CPU allocation
resources:
  - type: "container"
    alias: "main2"
    cpu: 4
    memory: 8GB