# .gitpod.yml
image:
  file: dockerfile

tasks:
  - name: Initialize Submodules
    init: |
      git submodule update --init --recursive
      cd nextflow
      make
  - name: Activate Conda Environment
    command: |
      source /opt/conda/etc/profile.d/conda.sh
      conda activate salmon
      nextflow -version
      salmon --version
