# .gitpod.yml
image:
  file: dockerfile

tasks:
  - name: Initialize Submodules
    init: |
      git submodule update --init --recursive
      cd nextflow
      make

  - name: Initialize Salmon
    init: |
      conda activate salmon