# .gitpod.yml
image:
  file: .gitpod.Dockerfile

tasks:
  - init: nextflow run main2.nf -params-file params.json
    command: nextflow run main2.nf

vscode:
  extensions:
    - nextflow.nextflow

# Increase memory and CPU allocation
resources:
  - type: "container"
    alias: "main2"
    cpu: 4
    memory: 8GB