# .gitpod.yml
image:
  file: tw599/nextflow-conda-gitpod

tasks:
  - name: Initialize Submodules
    init: |
      git submodule update --init --recursive
      cd nextflow
      make > /dev/null 2>&1